[package]
name = "thermal-printer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
escpos-rs = "0.4.2"
image = "0.23.14"
